language: php
services:
  - mysql
sudo: false

php:
  - 7.4
  - 7.3
  - 7.2

before_script:
  - composer install --dev --no-interaction
  - mysql -e 'create database pheasanttest;'

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
